### ISSUE TITLE
Invalid message is displayed in the Snackbar

### ISSUE THREAD

**Issue by ShivangiSingh17** [Catrobat/LunaAndCatTutorialGame#3]
**Summary**
When the user sign-up using the google account and under username textbox if a special character is inserted, it displays "Invalid Login" and an invalid message in the bar.
**Expected behavior**
Can be solved by displaying only  "Invalid Login" message in the snackbar.

**Would you like to work on this issue?**
Yes

**Screenshots of the issue**
 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/43827236/73295034-ecf9a780-422c-11ea-9e75-385141ff885e.gif)

**Comment by ShivangiSingh17** [comment]
I would like to work on this issue @wslany.

**Comment by ShivangiSingh17** [comment]
I would like to work on this issue @stefaniamak

**Comment by stefaniamak** [comment]
Hi @ShivangiSingh17 ! This is an issue for the app itself, not the Tutorial Game Project :) please write it down there instead of here!
